version: 2

sources:
  - name: dbt_gts
    database: snowflake_sample_data
    schema: tpch_sf100
    tables:
      - name: orders
        columns:
          - name: o_orderkey
          - name: o_orderstatus
            #data_tests: 
              #- test_column_for_null_values

      - name: lineitem
        columns:
          - name: l_orderkey
            data_tests:
              - not_null
              - relationships:
                  to: ref('orders')
                  field: o_orderkey
      

models:
  - name: stg_orders
    columns:
      - name: o_totalprice
        data_tests:
          - average_dollars_spent_greater_than_one
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 20
              row_condition: "o_totalprice is not null"
              strictly: True
    data_tests:
      - dbt_utils.expression_is_true:
          expression: "o_totalprice > 10"
          config:
            limit: 500
    


  - name: stg_lineitem
    columns:
      - name: l_orderkey
        data_type: number
      - name: l_partkey
        data_type: number
      - name: l_suppkey
        data_type: number
      - name: l_linenumber
        data_type: number
      - name: l_quantity
        data_type: number
      - name: l_extendedprice
        data_type: number
      - name: l_discount
        data_type: number
      - name: l_tax
        data_type: number
      - name: l_returnflag
        data_type: varchar
      - name: l_linestatus
        data_type: varchar
      - name: l_shipdate
        data_type: date
      - name: l_commitdate
        data_type: date
      - name: l_receiptdate
        data_type: date
      - name: l_shipinstruct
        data_type: varchar
      - name: l_shipmode
        data_type: varchar
      - name: l_comment
        data_type: varchar
