version: 2

sources:
  - name: dbt_gts
    database: snowflake_sample_data
    schema: tpch_sf100
    tables:
      - name: orders
        columns:
          - name: o_orderkey
            data_tests:
              - unique
              - not_null
      - name: lineitem
        columns:
          - name: l_orderkey
            data_tests:
              - unique
              - not_null
              - relationships:
                  to: ref('orders')
                  field: o_orderkey
