name: dbt Deployment Pipeline

on:
  push:
    branches:
      - prod
        staging
        dev
  pull_request:
    branches:
      - prod
        staging
        dev
  workflow_dispatch:  # Allows manual trigger from GitHub interface

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python (for dbt)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"  # Specify Python version

      # Install dbt and adapter (replace dbt-snowflake with your adapter)
      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake  # Use the adapter you need

      - name: Set up the dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "$DBT_PROFILE" > ~/.dbt/profiles.yml
        env:
          DBT_PROFILE: ${{ secrets.DBT_PROFILE }}

      # Conditionally set environment variables based on the branch
      - name: Set environment for dev branch
        if: github.ref == 'refs/heads/dev'
        run: echo "Running in dev environment"
        env:
          DBT_TARGET: ${{ secrets.DBT_DEV_ENV }}

      - name: Set environment for staging branch
        if: github.ref == 'refs/heads/staging'
        run: echo "Running in staging environment"
        env:
          DBT_TARGET: ${{ secrets.DBT_STG_ENV }}

      - name: Set environment for production branch
        if: github.ref == 'refs/heads/main'
        run: echo "Running in production environment"
        env:
          DBT_TARGET: ${{ secrets.DBT_MY_ENV }}

      # Run dbt commands
      - name: Run dbt commands for dev
        if: github.ref == 'refs/heads/dev'
        run: |
          dbt deps  # Install dbt dependencies
          dbt seed  # Load seeds (optional)
          dbt test --target dev  # Run tests for the specified environment
          dbt run --target dev  # Run models for the specified environment

      - name: Run dbt commands for staging
        if: github.ref == 'refs/heads/staging'
        run: |        
          dbt deps  # Install dbt dependencies
          dbt seed  # Load seeds (optional)
          dbt test --target staging  # Run tests for the specified environment
          dbt run --target staging  # Run models for the specified environment
          
      - name: Run dbt commands for prod
        if: github.ref == 'refs/heads/main'
        run: |         
          dbt deps  # Install dbt dependencies
          dbt seed  # Load seeds (optional)
          dbt test --target prod  # Run tests for the specified environment
          dbt run --target prod  # Run models for the specified environment
